### PR TITLE
iwinfo: print "radar detection" for those frequencies that are DFS aware

### PR DESCRIPTION
**Pull request by rmandrad**
enable the printout for those frequencies that are radar detected

use NL80211_FREQUENCY_ATTR_RADAR to determine the frequency is radar detected and print "RADAR DETECTION"

output

`iwinfo phy0.0-ap0 freqlist
  2.412 GHz (Band: 2.4 GHz, Channel 1) [NO_HT40-, NO_80MHZ, NO_160MHZ]
  2.417 GHz (Band: 2.4 GHz, Channel 2) [NO_HT40-, NO_80MHZ, NO_160MHZ]
  2.422 GHz (Band: 2.4 GHz, Channel 3) [NO_HT40-, NO_80MHZ, NO_160MHZ]
  2.427 GHz (Band: 2.4 GHz, Channel 4) [NO_HT40-, NO_80MHZ, NO_160MHZ]
  2.432 GHz (Band: 2.4 GHz, Channel 5) [NO_80MHZ, NO_160MHZ]
* 2.437 GHz (Band: 2.4 GHz, Channel 6) [NO_80MHZ, NO_160MHZ]
  2.442 GHz (Band: 2.4 GHz, Channel 7) [NO_80MHZ, NO_160MHZ]
  2.447 GHz (Band: 2.4 GHz, Channel 8) [NO_80MHZ, NO_160MHZ]
  2.452 GHz (Band: 2.4 GHz, Channel 9) [NO_80MHZ, NO_160MHZ]
  2.457 GHz (Band: 2.4 GHz, Channel 10) [NO_HT40+, NO_80MHZ, NO_160MHZ]
  2.462 GHz (Band: 2.4 GHz, Channel 11) [NO_HT40+, NO_80MHZ, NO_160MHZ]
  2.467 GHz (Band: 2.4 GHz, Channel 12) [NO_HT40+, NO_80MHZ, NO_160MHZ]
  2.472 GHz (Band: 2.4 GHz, Channel 13) [NO_HT40+, NO_80MHZ, NO_160MHZ]
  5.180 GHz (Band: 5 GHz, Channel 36) [NO_HT40-, INDOOR_ONLY]
  5.200 GHz (Band: 5 GHz, Channel 40) [INDOOR_ONLY]
  5.220 GHz (Band: 5 GHz, Channel 44) [INDOOR_ONLY]
  5.240 GHz (Band: 5 GHz, Channel 48) [INDOOR_ONLY]
  5.260 GHz (Band: 5 GHz, Channel 52) [INDOOR_ONLY, **RADAR DETECTION**]
  5.280 GHz (Band: 5 GHz, Channel 56) [INDOOR_ONLY, RADAR DETECTION]
  5.300 GHz (Band: 5 GHz, Channel 60) [INDOOR_ONLY, RADAR DETECTION]
  5.320 GHz (Band: 5 GHz, Channel 64) [NO_HT40+, INDOOR_ONLY, RADAR DETECTION]
  5.500 GHz (Band: 5 GHz, Channel 100) [NO_HT40-, RADAR DETECTION]
  5.520 GHz (Band: 5 GHz, Channel 104) [RADAR DETECTION]
  5.540 GHz (Band: 5 GHz, Channel 108) [RADAR DETECTION]
  5.560 GHz (Band: 5 GHz, Channel 112) [RADAR DETECTION]
  5.580 GHz (Band: 5 GHz, Channel 116) [RADAR DETECTION]
  5.600 GHz (Band: 5 GHz, Channel 120) [RADAR DETECTION]
  5.620 GHz (Band: 5 GHz, Channel 124) [RADAR DETECTION]
  5.640 GHz (Band: 5 GHz, Channel 128) [RADAR DETECTION]
  5.660 GHz (Band: 5 GHz, Channel 132) [RADAR DETECTION]
  5.680 GHz (Band: 5 GHz, Channel 136) [RADAR DETECTION]
  5.700 GHz (Band: 5 GHz, Channel 140) [RADAR DETECTION]
  5.720 GHz (Band: 5 GHz, Channel 144) [NO_HT40+, RADAR DETECTION]
  5.745 GHz (Band: 5 GHz, Channel 149) [NO_HT40-, NO_160MHZ, INDOOR_ONLY]
  5.765 GHz (Band: 5 GHz, Channel 153) [NO_160MHZ, INDOOR_ONLY]
  5.785 GHz (Band: 5 GHz, Channel 157) [NO_160MHZ, INDOOR_ONLY]
  5.805 GHz (Band: 5 GHz, Channel 161) [NO_160MHZ, INDOOR_ONLY]
  5.825 GHz (Band: 5 GHz, Channel 165) [NO_HT40+, NO_160MHZ, INDOOR_ONLY]
  5.955 GHz (Band: 6 GHz, Channel 1) [NO_HT40-, INDOOR_ONLY]
  5.975 GHz (Band: 6 GHz, Channel 5) [INDOOR_ONLY]
  5.995 GHz (Band: 6 GHz, Channel 9) [INDOOR_ONLY]
  6.015 GHz (Band: 6 GHz, Channel 13) [INDOOR_ONLY]
  6.035 GHz (Band: 6 GHz, Channel 17) [INDOOR_ONLY]
  6.055 GHz (Band: 6 GHz, Channel 21) [INDOOR_ONLY]
  6.075 GHz (Band: 6 GHz, Channel 25) [INDOOR_ONLY]
  6.095 GHz (Band: 6 GHz, Channel 29) [INDOOR_ONLY]
  6.115 GHz (Band: 6 GHz, Channel 33) [INDOOR_ONLY]
  6.135 GHz (Band: 6 GHz, Channel 37) [INDOOR_ONLY]
  6.155 GHz (Band: 6 GHz, Channel 41) [INDOOR_ONLY]
  6.175 GHz (Band: 6 GHz, Channel 45) [INDOOR_ONLY]
  6.195 GHz (Band: 6 GHz, Channel 49) [INDOOR_ONLY]
  6.215 GHz (Band: 6 GHz, Channel 53) [INDOOR_ONLY]
  6.235 GHz (Band: 6 GHz, Channel 57) [INDOOR_ONLY]
  6.255 GHz (Band: 6 GHz, Channel 61) [INDOOR_ONLY]
  6.275 GHz (Band: 6 GHz, Channel 65) [INDOOR_ONLY]
  6.295 GHz (Band: 6 GHz, Channel 69) [INDOOR_ONLY]
  6.315 GHz (Band: 6 GHz, Channel 73) [INDOOR_ONLY]
  6.335 GHz (Band: 6 GHz, Channel 77) [INDOOR_ONLY]
  6.355 GHz (Band: 6 GHz, Channel 81) [INDOOR_ONLY]
  6.375 GHz (Band: 6 GHz, Channel 85) [INDOOR_ONLY]
  6.395 GHz (Band: 6 GHz, Channel 89) [INDOOR_ONLY]
  6.415 GHz (Band: 6 GHz, Channel 93) [NO_HT40+, INDOOR_ONLY]
`

### CODE REVIEW

**Comment by systemcrash** [comment]
ping @Ansuel

**Comment by blogic** [comment]
I re-wrote iwinfo and all the shell based scripts in ucode and plan to push them shortly to main branch, c-based iwinfo is kinda EOL
--> https://git.openwrt.org/?p=openwrt/staging/blogic.git;a=shortlog;h=refs/heads/main

**Comment by rmandrad** [comment]
> I re-wrote iwinfo and all the shell based scripts in ucode and plan to push them shortly to main branch, c-based iwinfo is kinda EOL --> https://git.openwrt.org/?p=openwrt/staging/blogic.git;a=shortlog;h=refs/heads/main

have you included this feature ? showing frequencies that are DFS/Radar detected

**Comment by blogic** [comment]
@rmandrad no, but should be trivial to add

**Comment by rmandrad** [comment]
> @rmandrad no, but should be trivial to add

awesome here's a challenge beat 4 lines of code

**Comment by systemcrash** [comment]
@rmandrad do you feel up to making a commit for ucode DFS channels?

**Comment by blogic** [comment]
@systemcrash ucode wifi-scripts already implements this feature

**Comment by systemcrash** [comment]
Could you point to a commit, @blogic ?

**Comment by blogic** [comment]
grep RADAR_DETECTION .... figure it out yourself

**Comment by systemcrash** [comment]
https://github.com/openwrt/openwrt/blob/874e0accae5121534259cc8b1bd3107bd104dd24/package/network/config/wifi-scripts/files-ucode/usr/share/ucode/iwinfo.uc#L344 ?

**Pull request closed without merging**
