### PR TITLE
devices: add Cypress CYW43455 variant found on the Raspberry Pi 5

### PR DESCRIPTION
**Pull request by mj22226**
This adds a Cypress CYW43455 variant found on the Raspberry Pi 5 .

### CODE REVIEW

**Comment by Ansuel** [comment]
Can you change the commit description to something like `Add Cypress CYW43455 variant found on the Raspberry Pi 5.`

**Comment by mj22226** [comment]
@Ansuel is ok now?

**Comment by Ansuel** [comment]
Yes will merge later.

**Comment by Ansuel** [comment]
@mj22226 sorry but can you rebase this on top of master?

**Comment by mj22226** [comment]
@Ansuel rebased

**Pull request merged**
